language: node_js

node_js:
  - 8

cache: yarn

branches:
  only:
    - master

script:
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
